version: "3.9" 
services: 
  mysql_knex:
    container_name: biblioteca
    hostname: biblioteca
    image: mysql:latest  
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
      - --bind-address=0.0.0.0
    volumes: 
      - "/d/faculdade/1 semestre/projeto integrado sintese de dados/DB:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: lucas
      MYSQL_PASSWORD: 123456
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s 
